name: Deploy to WordPress SVN
on:
  release:
    types:
      - published
jobs:
  tag:
    name: New Release of adCAPTCHA WordPress Plugin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up PHP
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "7.4"

    - name: Install Composer Dependencies
      uses: "ramsey/composer-install@v3"
      with:
        composer-options: "--no-dev --optimize-autoloader"

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: adcaptcha
        ASSETS_DIR: .wordpress-org
        ASSETS_ONLY: true
        