name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: php-actions/composer@v6

    - name: Run PHP Unit Tests
      uses: php-actions/phpunit@v3